### ISSUE TITLE
Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#46] opened 2021-05-12 07:26 UTC
When searching for a term in the Wikibase (both dev and prod), there is this error showing in the console:

VM21:6 Uncaught TypeError: Cannot read property 'config' of undefined
    at HTMLFormElement.<anonymous> (<anonymous>:6:73)
    at HTMLFormElement.dispatch (load.php?lang=en&modules=jquery|jquery.ui&skin=vector&version=11ak3:69)
    at HTMLFormElement.elemData.handle (load.php?lang=en&modules=jquery|jquery.ui&skin=vector&version=11ak3:66)
    at Object.trigger (load.php?lang=en&modules=jquery|jquery.ui&skin=vector&version=11ak3:115)
    at HTMLFormElement.<anonymous> (load.php?lang=en&modules=jquery|jquery.ui&skin=vector&version=11ak3:116)
    at Function.each (load.php?lang=en&modules=jquery|jquery.ui&skin=vector&version=11ak3:5)
    at jQuery.fn.init.each (load.php?lang=en&modules=jquery|jquery.ui&skin=vector&version=11ak3:3)
    at jQuery.fn.init.trigger (load.php?lang=en&modules=jquery|jquery.ui&skin=vector&version=11ak3:116)
    at <anonymous>:57:400
    at $.<computed>.<computed>.select (<anonymous>:83:582)

**Comment by D063520** [comment] 2021-07-06 08:44
can you try again, I do not see it anymore, but I also did not change anything ....

**Comment by madewild** [comment] 2021-07-06 08:46
I still see it in the console, for instance on https://linkedopendata.eu/w/index.php?search=paris&search=paris&title=Special%3ASearch&go=Go

**Comment by D063520** [comment] 2021-07-06 08:53
<img width="1680" alt="Screenshot 2021-07-06 at 10 52 34" src="https://user-images.githubusercontent.com/10883585/124571669-4b767c80-de48-11eb-8dd3-abfecd016ac1.png">
strange ... anyway is it important, everything is working no? Will probably go away in the next upgrade

**Comment by madewild** [comment] 2021-07-06 08:56
don't worry, just to keep in mind ;)

**Comment by madewild** [comment] 2021-09-21 10:12
The error only pops up in the console when searching with the top-right search bar, so it's probably linked to the search-as-you-type (aka autocomplete).

**Comment by D063520** [comment] 2022-04-28 18:53
I cannot reproduce this anymore ... probably fixed with the new version

**Comment by madewild** [comment] 2022-04-29 08:08
But it's fine on https://cluster.linkedopendata.eu/w/index.php?search=paris&title=Special%3ASearch&profile=default&fulltext=1
So it looks like the issue will resolve itself by moving to the cluster :)

**Closed** 2022-04-29 08:13 UTC
Labels: minor
